- hosts: all
  gather_facts: False

  tasks:
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 30
      timeout: 600
      sleep: 30
    connection: local

  - name: install python on ubuntu
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 30

- hosts: master
  gather_facts: False
  become: true
  roles:
    - ebs_config